---
:development: &defaults
  :adapter: mysql
  :database: codejenzi_development
  :username: codejenzi
  :password: suspectzero
  :host: localhost

:test:
  <<: *defaults
  :database: codejenzi_test

:production:
  <<: *defaults
  :database: codejenzi

:rake:
  <<: *defaults

 
rake:
  <<: *defaults
